version: "3"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        HOMEDIR: $HOMEDIR
    command: sleep infinity
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /work
      - type: bind
        source: ~/.aws/
        target: ${HOMEDIR}/.aws/
      - type: bind
        source: ~/.config
        target: ${HOMEDIR}/.config
      - type: bind
        source: ~/.config/.gh
        target: ${HOMEDIR}/.config/.gh
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
      - type: volume
        source: commandhistory
        target: /commandhistory

volumes:
  commandhistory:
